name: Sync pictures

on:
    schedule:
        - cron: '0 22 * * *'
    workflow_dispatch:
permissions:
  contents: write
  deployments: write
jobs:
    Sync:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Clone from origin repo
              run: |
                git config --global user.email "action@github.com"
                git config --global user.name "GitHub Action"
                git clone https://github.com/PCL-Community/worldhim-alist-backup.git
            
            - name: Get files
              run: |
                cd worldhim-alist-backup
                mv randpic ..
                cd ..
                rm -rf worldhim-alist-backup
                rm -rf meme
            
            - name: Run script
              run: |
                python sync.py
            
            - name: Commit changes
              if: steps.check.outputs.changed == 'true'
              run: |
                git config --global user.email "action@github.com"
                git config --global user.name "GitHub Action"
                git add .
                git commit -m "Sync"
                git push
            
                